/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#131315",
        "on-error-container": "#ffdad6",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "on-secondary": "#353026",
        "surface-container-lowest": "#0e0e10",
        "primary-fixed-dim": "#dcc39a",
        "on-surface": "#e5e1e4",
        "on-secondary-container": "#bdb4a6",
        "on-primary-fixed": "#261901",
        "tertiary": "#d0cfc8",
        "on-background": "#e5e1e4",
        "outline-variant": "#4c463c",
        "surface-container-high": "#2a2a2c",
        "secondary-fixed": "#ebe1d2",
        "primary": "#e5cba2",
        "on-surface-variant": "#cfc5b8",
        "surface-container-low": "#1c1b1e",
        "inverse-on-surface": "#313032",
        "on-primary-fixed-variant": "#554425",
        "primary-container": "#c8b088",
        "surface-tint": "#dcc39a",
        "on-secondary-fixed": "#1f1b12",
        "secondary-container": "#4c463b",
        "surface-variant": "#353437",
        "error-container": "#93000a",
        "surface-container-highest": "#353437",
        "on-secondary-fixed-variant": "#4c463b",
        "tertiary-container": "#b5b3ad",
        "on-tertiary-fixed": "#1b1c18",
        "primary-fixed": "#f9dfb4",
        "outline": "#988f83",
        "surface-container": "#201f22",
        "on-primary-container": "#544323",
        "on-primary": "#3d2e10",
        "tertiary-fixed-dim": "#c8c6c0",
        "inverse-primary": "#6f5c3a",
        "tertiary-fixed": "#e4e2db",
        "secondary": "#cfc5b7",
        "secondary-fixed-dim": "#cfc5b7",
        "surface-bright": "#39393b",
        "on-tertiary-container": "#454541",
        "background": "#131315",
        "surface": "#131315",
        "on-tertiary": "#30312c",
        "inverse-surface": "#e5e1e4",
        "on-tertiary-fixed-variant": "#474742"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-2xs": "0.25rem",
        "margin-mobile": "1.5rem",
        "space-xl": "2.5rem",
        "space-3xl": "6rem",
        "space-lg": "1.5rem",
        "gutter-mobile": "1rem",
        "margin-desktop": "5rem",
        "space-md": "1rem",
        "space-xs": "0.5rem",
        "space-4xl": "10rem",
        "space-2xl": "4rem",
        "space-sm": "0.75rem",
        "gutter-desktop": "2rem"
      },
      fontFamily: {
        "label-coordinate": ["Space Grotesk"],
        "body-md": ["Plus Jakarta Sans"],
        "headline-sm": ["EB Garamond"],
        "caption": ["Plus Jakarta Sans"],
        "display-xl-mobile": ["EB Garamond"],
        "headline-md": ["EB Garamond"],
        "display-xl": ["EB Garamond"],
        "body-lg": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["EB Garamond"],
        "label-technical": ["Space Grotesk"],
        "headline-lg": ["EB Garamond"],
        "body-sm": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "label-coordinate": ["9px", { lineHeight: "12px", letterSpacing: "0.22em", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "26px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "32px", letterSpacing: "0em", fontWeight: "400" }],
        "caption": ["12px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "400" }],
        "display-xl-mobile": ["44px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "display-xl": ["80px", { lineHeight: "88px", letterSpacing: "-0.03em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "30px", letterSpacing: "-0.01em", fontWeight: "300" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "label-technical": ["11px", { lineHeight: "14px", letterSpacing: "0.14em", fontWeight: "500" }],
        "headline-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "22px", letterSpacing: "0.01em", fontWeight: "400" }]
      }
    }
  }
};
